
# from dataclasses import dataclass, field
from typing import Callable # , Any
# from datetime import datetime, timezone
# from types import MappingProxyType


# @dataclass
# class OutputPostprocessor:
#     key: str
#     output_postprocessor: Callable[[Any], Any]
#     registered_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc)) # I don't think I need it, but love when all is logged, all timestamps...


_output_postprocessors = {}


# def register_output_postprocessor(output_postprocessor: OutputPostprocessor) -> None:
#     """lol auto-generated by code completion"""
#     _output_postprocessors[output_postprocessor.key] = output_postprocessor

def register_output_postprocessor(name: str, fn: Callable) -> None:
    """lol auto-generated by code completion"""
    # output_postprocessor = OutputPostprocessor(
    #     key = name,
    #     output_postprocessor = fn,
    # )
    output_postprocessor = fn
    _output_postprocessors[name] = output_postprocessor

def get_output_postprocessor(output_postprocessor_name: str) -> Callable | None:
    """lol auto-generated by code completion"""
    return _output_postprocessors.get(output_postprocessor_name, None)

# output_postprocessors = MappingProxyType(_output_postprocessors)
output_postprocessors = _output_postprocessors
